config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  
  

  resources :equipment
 

  resources :protocols

  resources :companies
  
  resources :users

  
  resources :sessions

  root 'protocols#index'
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
 
  
  get '/protocols/:id/generate' => 'protocols#generate', :as => 'generate_protocol'
  
  get 'products/:id' => 'catalog#view'

  
  resources :protocols do
    resources :equipments
  end
  resources :companies do
    resources :users
  end
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  belongs_to :company
  has_many :protocol
  
  # has_one :protocol, :class_name => 'Protocol', :foreign_key => 'user_to_id'
  
  
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_presence_of :name
  validates_presence_of :company_id
  validates_uniqueness_of :email
  
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate
  def new
   
    @user = User.new
  end

  def show
    
  end
  
  def edit
    
  end
  
  def index
    @users = User.all
  end
  
 #meotdy do |controllera|
    # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
 
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end  
    
  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :company_id, :privilege)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong><%= pluralize(@user.errors.count, "error") %> prohibited this protocol from being saved:</strong>

        <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>


  <div class="col-sm-6 col-md-4">
      <div class="form-group">
          <label><%= f.label :company_id %></label><br/>
          <%= select_tag('user[company_id]',options_from_collection_for_select(Company.all, "id", "name", @user.company_id),{class: "form-control"}) %>
        </div>
        <div class="form-group">
            <%= f.label :name, "Full name" %><br>
            <%= f.text_field :name, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %><br>
            <%= f.text_field :email, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password %><br>
            <%= f.password_field :password, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation %><br>
            <%= f.password_field :password_confirmation, :class => "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :privilege,'Admin' %><br>
            <%= f.check_box :privilege, :class => "form-control" %>
        </div>


        <div class="actions">
            <%= link_to 'Back', protocols_path, :class=>"btn btn-default"  %>
            <%= f.submit 'Create User', :class=>"btn btn-default" %>
        </div>
      <% end %>
  </div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
# encoding: utf-8
<% @userr = User.all %>
<h1>Listing users <%= @userr.count %> </h1>

<%#*Forumlarz wyszukujący tresc%>


<br><br>

<table class="table table-hover">
  <thead>
    <tr>

      <th>Company</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Registration date</th>
      

<%#*<th>Owner</th>%>
<%#*<th>Email</th>%>
<%#*<th>Telephone</th>%>
<%#*<th>IP</th>%>
<%#*<th>Updated</th>%>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>

        <td><%= user.company.name %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
       

  <%#*<td><%= user.owner.blank? ? "-" : user.owner.force_encoding('utf-8') </td>%>
  <%#*<td><%= user.email.blank? ? "-" : (mail_to user.email) </td>%>
  <%#*<td><%= user.telephone.blank? ? "-" : user.telephone </td>%>
  <%#*<td><%= user.ip_address.blank? ? "-" : user.ip_address </td>%> 
  <%#*<td><%= user.updated_at </td>%>

       
        
        <td style="text-align: center;"><%= link_to 'Show', user, :class=>"btn btn-primary btn-sm" %></td>
        <td style="text-align: center;"><%= link_to 'Edit', edit_user_path(user), :class=>"btn btn-primary btn-sm"  %></td>
        <td style="text-align: center;"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<%= link_to 'New User', new_user_path,:class=>"btn btn-default" %> 
<%= link_to 'Back', users_path,:class=>"btn btn-default" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @user.company.name %>
</p>
<p>
  <strong>Full name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Date:</strong>
  <%= @user.created_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user), :class=>"btn btn-default" %> |
<%= link_to 'Back', users_path, :class=>"btn btn-default" %>