config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  
  

  resources :equipment
 

  resources :protocols

  resources :companies
  
  resources :users

  
  resources :sessions

  root 'protocols#index'
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
 
  
  get '/protocols/:id/generate' => 'protocols#generate', :as => 'generate_protocol'
  
  get 'products/:id' => 'catalog#view'

  
  resources :protocols do
    resources :equipments
  end
  resources :companies do
    resources :users
  end
  
  
  
  

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :users, :dependent => :destroy
   validates :name, :presence => true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
      <strong><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</strong>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-sm-6 col-md-4">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="actions">
      <%= link_to 'Back', companies_path ,:class=>"btn btn-default"%>
      
    <%= f.submit 'Create company', :class=>"btn btn-default" %>
  </div>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company,:class=>"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_company_path(company),:class=>"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path,:class=>"btn btn-default" %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company), :class=>"btn btn-default" %> |
<%= link_to 'Back', companies_path, :class=>"btn btn-default" %>