config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  
  

  resources :equipment
 

  resources :protocols

  resources :companies
  
  resources :users

  
  resources :sessions

  root 'protocols#index'
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
 
  
  get '/protocols/:id/generate' => 'protocols#generate', :as => 'generate_protocol'
  
  get 'products/:id' => 'catalog#view'

  
  resources :protocols do
    resources :equipments
  end
  resources :companies do
    resources :users
  end
  
  
  
  

end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  has_many :equipments, :dependent => :destroy
  belongs_to :user
    
  
  belongs_to :user_to, :class_name => 'User', :foreign_key => 'user_to_id'
  belongs_to :company_to, :class_name => 'Company', :foreign_key => 'company_to_id'
  belongs_to :company, :class_name => 'Company', :foreign_key => 'company_id'

  validates :user_id, presence: true
    
 accepts_nested_attributes_for :equipments,  :allow_destroy => true
 
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |protocol|
        csv << protocol.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_action :set_protocol, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, except: [:index, :show]
  
  helper_method :generate
  # GET /protocols
  # GET /protocols.json
  
  def index
    @protocols = Protocol.order(:number)
   
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
    
    @equip = Protocol.find(params[:id]).equipments
  end
  
  def generate 
    require 'spreadsheet'
    @equip = Protocol.find(params[:id])
    
   
        
    #spreadsheet = StringIO.new 
    #    book = Spreadsheet::Workbook.new
    #    sheet1 = book.create_worksheet
    #    sheet1.name = 'My First Worksheet'
    #    sheet1[1,0] = 'Japan'
            
    book = Spreadsheet.open 'public/xls/test.xls'
    sheet = book.worksheet 0
            
    buffer = StringIO.new
    book.write(buffer)
    buffer.rewind
    
    
    
    
    book.write 'public/xls/data.xls'
    
  
    send_file 'public/xls/data.xls', :filename => @equip.number, :type =>  "application/vnd.ms-excel", :stream => false
    
    #    send_data spreadsheet.string, :filename => "yourfile.xls", :type =>  "application/vnd.ms-excel"

    
  end
  

  
  

  # GET /protocols/new
  def new
    @protocol = Protocol.new
    
    #linia dodajaca nowy equipment na starcie
    @protocol.equipments.build
    
  end

  # GET /protocols/1/edit
  def edit
  end
  
  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new(protocol_params)
   
    
    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render :show, status: :created, location: @protocol }
      else
        format.html { render :new }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protocols/1
  # PATCH/PUT /protocols/1.json
  def update
 
    respond_to do |format|
      if @protocol.update(protocol_params)
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @protocol }
      else
        format.html { render :edit }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol.destroy
    respond_to do |format|
      format.html { redirect_to protocols_url, notice: 'Protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_protocol
    @protocol = Protocol.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def protocol_params
    params.require(:protocol).permit(:date, :user_id, :number, :user_to_id, :company_id, :company_to_id, equipments_attributes: [:id, :name, :mark, :serial, :quantity, :brutto, :v_brutto, :comments, :_destroy])
  end
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
  
  
end

app/views/protocols/_form.html.erb
<%= nested_form_for(@protocol) do |f| %>
  <% if @protocol.errors.any? %>
    <div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
      <strong><%= pluralize(@protocol.errors.count, "error") %> prohibited this protocol from being saved:</strong>

      <ul>
        <% @protocol.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @last = Protocol.order("created_at").last.number %>
  <%  @last+=1 %>
<div class="col-sm-6 col-md-4">
  <div class="form-group">
    <%= f.label :number %><br>
    <%= f.text_field :number, :value => @last, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, "From"%><br>
    <%= f.text_field :user_id, :value => current_user.name, :disabled => true, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :user_to_id, "To"%><br>

    <%= f.collection_select :user_to_id, User.all, :id, :name, {prompt: "Select a user"}, {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :company_id, "From"%><br>

    <%= f.collection_select :company_id, Company.all, :id, :name, {prompt: "Select a user"}, {class: "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :company_to_id, "To"%><br>

    <%= f.collection_select :company_to_id, Company.all, :id, :name, {prompt: "Select a user"}, {class: "form-control"}  %>
  </div>

<%#*//--------------------------------------------------------------------------%>

  <%= f.fields_for :equipments do |ff| %>
    <table class="equip">
      <tr>
        <td>Name:</td><td><%= ff.text_field :name, :class => "form-control" %></td>  
        <td>Mark: </td><td><%= ff.text_field :mark,  :class => "form-control" %></td>
        <td>Serial:</td><td><%= ff.text_field :serial, :class => "form-control" %></td>
        <td>Quantity:</td><td><%= ff.text_field :quantity, :onkeyup => "doQuan(this);", :class => "form-control" %></td>
        <td>Brutto:</td><td><%= ff.text_field :brutto,  :onkeyup => "doBrut(this);", :class => "form-control" %></td> 
        <td>Brutto value:</td><td><%= ff.text_field :v_brutto, :placeholder => "-", :class => "form-control" %></td>        
        <td>Comments:</td><td><%= ff.text_field :comments, :class => "form-control" %></td>
        <td><%= ff.link_to_remove "Remove", :class=>"btn btn-default" %></td>
      </tr>
    </table><br/>
  <% end %>
    
  <p><%= f.link_to_add "Add a equipment", :equipments, :class=>"btn btn-default" %></p>

<%#*//--------------------------------------------------------------------------%>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date,{class: "form-control"} %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :number, :value => @last %>
  <div class="actions">
      <%= link_to 'Back', protocols_path, :class=>"btn btn-default" %>
    <%= f.submit 'Create protocol', :class=>"btn btn-default" %>
  </div>
  </div>
<% end %>

app/views/protocols/edit.html.erb
<h1>Editing protocol</h1>

<%= render 'form' %>

app/views/protocols/index.html.erb
<% if notice %>
  <div class='alert alert-success'>
      <strong>Done!</strong>
      <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>Listing protocols</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Nr.</th>
            <th>Full name</th>
            <th>Date</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @protocols.each do |protocol| %>
          <tr>
              <td><%= protocol.number %></td>
              <%
              pname = protocol.user.try(:name) ? protocol.user.name : "brak"
                     
              %>
              <td><%= pname %></td>
              <td><%= protocol.date %></td>
              <td><%= link_to 'Show', protocol,:class=>"btn btn-primary btn-sm" %></td>
              <td><%= link_to 'Edit', edit_protocol_path(protocol),:class=>"btn btn-primary btn-sm" %></td>
              <td><%= link_to 'Destroy', protocol, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-primary btn-sm",:class=>"btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
    </tbody>
</table>

<br>


<%= link_to 'New Protocol', new_protocol_path ,:class=>"btn btn-default" %>

app/views/protocols/new.html.erb
<h1>New protocol</h1>

<%= render 'form' %>

app/views/protocols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nr.</strong>
  <%= @protocol.number %>
</p>
<p>
  <strong>From:</strong>
  <%= @protocol.user.name %>
</p>
<p>
  <strong>To:</strong>

  <%=  @protocol.user_to.name %>
</p>
<p>
  <strong>From:</strong>

  <%=  @protocol.company.name %>
</p>
<p>
  <strong>To:</strong>

  <%=  @protocol.company_to.name %>
</p>
<p>
<table class="table">
  <thead>
    <tr>
      <th>Lp.</th>
      <th>Name</th>
      <th>Mark</th>
      <th>Serial</th>
      <th>Quantity</th>
      <th>Brutto</th>
      <th>V brutto</th>
      <th>Comments</th>
     
    </tr>
  </thead>

  <tbody>
   
    <% @equip.each_with_index do |equipment,i| %>
      <tr>
        <td><%= i + 1 %> </td>
        <td><%= equipment.name %></td>
        <td><%= equipment.mark %></td>
        <td><%= equipment.serial %></td>
        <td><%= equipment.quantity %></td>
        <td><%= equipment.brutto %></td>
        <td><%= equipment.v_brutto %></td>
        <td><%= equipment.comments %></td>
     
      </tr>
    <% end %>
  </tbody>
</table>
</p>
<p>
  <strong>Date:</strong>
  <%= @protocol.date %>
</p>

<%= link_to 'Edit', edit_protocol_path(@protocol), :class=>"btn btn-default" %> 
<%= link_to 'Back', protocols_path, :class=>"btn btn-default" %>
<%= link_to 'Generate XLS', generate_protocol_path(@protocol) , :class=>"btn btn-success" %>

app/views/protocols/show.xls.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.xls" %>

app/views/protocols/show2.html.erb
<table border="1">
    <tr>
        <td></td><td>Protokół przekazania NR: <b><%= @protocol.number %></b></td><td>FOR-0<%= @protocol.number %>-PP</td>
    </tr>
    <tr>
        <td><b>ZATWIERDZAM</b></td><td></td><td>Egz nr: 1</td>
    </tr>
    <tr>
        <td>...............</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
    </tr>
      
    <tr>
        <td></td>
    </tr>
      
    <tr>
        <td></td>
    </tr>
      
    <tr>
        <td></td>
    </tr>
      

</table>

<%= link_to 'Edit', edit_protocol_path(@protocol) %> |
<%= link_to 'Back', protocols_path %>