config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  
  

  resources :equipment
 

  resources :protocols

  resources :companies
  
  resources :users

  
  resources :sessions

  root 'protocols#index'
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
 
  
  get '/protocols/:id/generate' => 'protocols#generate', :as => 'generate_protocol'
  
  get 'products/:id' => 'catalog#view'

  
  resources :protocols do
    resources :equipments
  end
  resources :companies do
    resources :users
  end
  
  
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Przekazanie</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag :defaults, "nested_form" %>

        <%= csrf_meta_tags %>
    </head>
    <body>
       
        <div class="container">
            <div class="row">
                <nav role="navigation" class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="#" class="navbar-brand">Protokoły Przekazania</a>
                    </div>
                    <!-- Collection of nav links and other content for toggling -->
                    <div id="navbarCollapse" class="collapse navbar-collapse">

                        <ul class="nav nav-pills">
                            <li> <%= nav_link raw("<span class='glyphicon glyphicon-list-alt'> </span> Protocols"), protocols_path  %></li>
                            <% if current_user %>
                            <li> <%= nav_link raw("<span class='glyphicon glyphicon-calendar'> </span> Companies"), companies_path  %></li>

                             
                              <% if current_user.privilege == 1%>
                            <li> <%= nav_link raw("<span class='glyphicon glyphicon-globe'> </span> Users"), users_path  %></li>
                               
                              <% end %>
                            <% end %>


                            <ul class="nav navbar-pills navbar-right">
                                <% if current_user %>
                                  <li> <%= nav_link raw("<span class='glyphicon glyphicon-off'> </span> Log out (#{current_user.name})"), log_out_path  %></li>
                                <% else %>
                                  <li> <%= nav_link raw("<span class='glyphicon glyphicon-user'> </span> Log In"), log_in_path  %></li>

                                <% end %>
                            </ul> 
                        </ul>

                    </div>
                </nav>
            </div>
        </div>


<div class="jumbotron">
        <div class="container">
            <div class="row">

                <%= yield %>

            </div>
        </div>
</div>








    </body>
</html>